const ROLES = [
  "PHARMA_COMPANY",
  "MR",
  "INDEPENDENT_MR",
  "PHARMACY",
  "STOCKIST",
  "DISTRIBUTOR",
  "ADMIN",
];

const PUBLIC_ROLES = [
  "PHARMA_COMPANY",
  "MR",
  "INDEPENDENT_MR",
  "PHARMACY",
  "STOCKIST",
  "DISTRIBUTOR",
];

const ACCOUNT_STATUSES = ["PENDING_VERIFICATION", "ACTIVE", "SUSPENDED", "REJECTED"];

const WORK_MODES = ["FIELD", "HYBRID", "REMOTE"];
const AVAILABILITY_STATUSES = ["AVAILABLE", "BUSY", "ON_LEAVE"];

const OPPORTUNITY_TYPES = ["MR_HIRING", "TERRITORY_EXPANSION", "DISTRIBUTION", "PRODUCT_PROMOTION"];
const OPPORTUNITY_STATUSES = ["OPEN", "CLOSED", "FILLED"];
const APPLICATION_STATUSES = ["PENDING", "SHORTLISTED", "ACCEPTED", "REJECTED"];

const URGENCY_LEVELS = ["LOW", "NORMAL", "HIGH"];
const REQUIREMENT_STATUSES = ["OPEN", "MATCHED", "CLOSED"];

const CONNECTION_STATUSES = ["PENDING", "ACCEPTED", "DECLINED"];

const APPOINTMENT_MODES = ["PHYSICAL", "VIDEO"];
const APPOINTMENT_STATUSES = [
  "CONFIRMED",
  "RUNNING_LATE",
  "RESCHEDULE_REQUESTED",
  "CANCELLED",
  "EMERGENCY",
  "COMPLETED",
];
const DISRUPTION_REASONS = [
  "WEATHER",
  "HEALTH",
  "TRAVEL",
  "TRAFFIC",
  "EMERGENCY",
  "PREVIOUS_DELAY",
  "UNAVAILABLE",
  "OTHER",
];

const NOTIFICATION_TYPES = [
  "CONNECTION_REQUEST",
  "APPOINTMENT_UPDATE",
  "MESSAGE",
  "OPPORTUNITY_MATCH",
  "REQUIREMENT_MATCH",
  "VERIFICATION_UPDATE",
  "SYSTEM",
];

const DOC_TYPES = ["DRUG_LICENSE", "GST", "ID_PROOF", "BUSINESS_REG", "OTHER"];
const DOC_STATUSES = ["PENDING", "APPROVED", "REJECTED"];

const PRODUCT_CATEGORIES = [
  "Dermatology",
  "Cardiology",
  "Pediatrics",
  "Neurology",
  "Oncology",
  "Diabetology",
  "Orthopedics",
  "Gynecology",
  "General Medicine",
  "Nutraceuticals",
];

module.exports = {
  ROLES,
  PUBLIC_ROLES,
  ACCOUNT_STATUSES,
  WORK_MODES,
  AVAILABILITY_STATUSES,
  OPPORTUNITY_TYPES,
  OPPORTUNITY_STATUSES,
  APPLICATION_STATUSES,
  URGENCY_LEVELS,
  REQUIREMENT_STATUSES,
  CONNECTION_STATUSES,
  APPOINTMENT_MODES,
  APPOINTMENT_STATUSES,
  DISRUPTION_REASONS,
  NOTIFICATION_TYPES,
  DOC_TYPES,
  DOC_STATUSES,
  PRODUCT_CATEGORIES,
};
