const ROLES = [
  "PHARMA_COMPANY",
  "MR",
  "PHARMACY",
  "DISTRIBUTOR_STOCKIST",
  "DOCTOR",
  "ADMIN",
];

const PUBLIC_ROLES = [
  "PHARMA_COMPANY",
  "MR",
  "PHARMACY",
  "DISTRIBUTOR_STOCKIST",
  "DOCTOR",
];

const ACCOUNT_STATUSES = [
  "PENDING_VERIFICATION",
  "ACTIVE",
  "SUSPENDED",
  "REJECTED",
];

const WORK_MODES = ["FIELD", "HYBRID", "REMOTE"];

const AVAILABILITY_STATUSES = ["AVAILABLE", "BUSY", "ON_LEAVE"];

const OPPORTUNITY_TYPES = [
  "MR_HIRING",
  "TERRITORY_EXPANSION",
  "DISTRIBUTION",
  "PRODUCT_PROMOTION",
];

const OPPORTUNITY_STATUSES = ["OPEN", "CLOSED", "FILLED"];

const APPLICATION_STATUSES = [
  "PENDING",
  "SHORTLISTED",
  "ACCEPTED",
  "REJECTED",
];

const URGENCY_LEVELS = ["LOW", "NORMAL", "HIGH"];

const REQUIREMENT_STATUSES = ["OPEN", "MATCHED", "CLOSED"];

const CONNECTION_STATUSES = ["PENDING", "ACCEPTED", "DECLINED"];

const APPOINTMENT_MODES = ["PHYSICAL", "VIDEO"];

const APPOINTMENT_STATUSES = [
  "REQUESTED",
  "CONFIRMED",
  "RUNNING_LATE",
  "RESCHEDULE_REQUESTED",
  "DECLINED",
  "CANCELLED",
  "EMERGENCY",
  "COMPLETED",
];

const DISRUPTION_REASONS = [
  "WEATHER",
  "HEALTH",
  "TRAVEL",
  "TRAFFIC",
  "EMERGENCY",
  "PREVIOUS_DELAY",
  "UNAVAILABLE",
  "OTHER",
];

const NOTIFICATION_TYPES = [
  "CONNECTION_REQUEST",
  "APPOINTMENT_UPDATE",
  "MESSAGE",
  "OPPORTUNITY_MATCH",
  "REQUIREMENT_MATCH",
  "VERIFICATION_UPDATE",
  "SYSTEM",
];

const DOC_TYPES = [
  "DRUG_LICENSE",
  "GST",
  "ID_PROOF",
  "MEDICAL_REGISTRATION",
  "COMPANY_AUTHORIZATION",
  "BUSINESS_REG",
  "OTHER",
];

const DOC_STATUSES = ["PENDING", "APPROVED", "REJECTED"];

const PRODUCT_CATEGORIES = [
  "Dermatology",
  "Cardiology",
  "Pediatrics",
  "Neurology",
  "Oncology",
  "Diabetology",
  "Orthopedics",
  "Gynecology",
  "General Medicine",
  "Nutraceuticals",
];

const LEAD_STAGES = [
  "NEW",
  "REVIEWED",
  "CONTACT_REQUESTED",
  "CONNECTED",
  "CONVERSATION_STARTED",
  "APPOINTMENT_REQUESTED",
  "APPOINTMENT_SCHEDULED",
  "APPOINTMENT_COMPLETED",
  "QUALIFIED",
  "FOLLOW_UP",
  "PARTNERSHIP_DISCUSSION",
  "CONVERTED",
  "CLOSED_WON",
  "CLOSED_LOST",
  "NOT_INTERESTED",
  "UNREACHABLE",
  "DUPLICATE",
  "DISQUALIFIED",
  "EXPIRED",
  "REPORTED",
  "SUSPENDED",
];

const CLOSED_LEAD_STAGES = [
  "CLOSED_WON",
  "CLOSED_LOST",
  "NOT_INTERESTED",
  "UNREACHABLE",
  "DUPLICATE",
  "DISQUALIFIED",
  "EXPIRED",
  "REPORTED",
  "SUSPENDED",
];

function normalizeRole(role) {
  if (role === "COMPANY") return "PHARMA_COMPANY";
  if (
    role === "INDEPENDENT_MR" ||
    role === "MEDICAL_REPRESENTATIVE"
  ) {
    return "MR";
  }
  if (
    role === "STOCKIST" ||
    role === "DISTRIBUTOR"
  ) {
    return "DISTRIBUTOR_STOCKIST";
  }
  return role;
}

module.exports = {
  ROLES,
  PUBLIC_ROLES,
  ACCOUNT_STATUSES,
  WORK_MODES,
  AVAILABILITY_STATUSES,
  OPPORTUNITY_TYPES,
  OPPORTUNITY_STATUSES,
  APPLICATION_STATUSES,
  URGENCY_LEVELS,
  REQUIREMENT_STATUSES,
  CONNECTION_STATUSES,
  APPOINTMENT_MODES,
  APPOINTMENT_STATUSES,
  DISRUPTION_REASONS,
  NOTIFICATION_TYPES,
  DOC_TYPES,
  DOC_STATUSES,
  PRODUCT_CATEGORIES,
  LEAD_STAGES,
  CLOSED_LEAD_STAGES,
  normalizeRole,
};